name: udd-update-dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "42 19 * * *"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.20.2
      - name: Update dependencies
        run: |
          deno run -A https://deno.land/x/udd/main.ts xelm.ts
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: pr
        with:
          commit-message: "update deps"
          title: Update dependencies
          body: >
            Dependencies updated by [udd](https://github.com/hayd/deno-udd).
          branch: update-deps
          author: GitHub <noreply@github.com>
          delete-branch: true
      - name: Retrieve commit sha
        id: commit
        run: |
          echo "::set-output name=sha::$(git rev-parse HEAD)"
